server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    #gateway:
      #discovery:
        #locator:
          #enabled: true
    zookeeper:
      connect-string: localhost:2181